- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
- name: Print all available facts
  hosts: all
  ansible.builtin.debug:
    var: ansible_facts
- name: Retrieve host vars
  hosts: all
  tasks:
    - debug:
        var=hostvars[inventory_hostname]
