- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
- name: Retrieve host vars
  hosts: all
  tasks:
    - debug:
        var=hostvars[inventory_hostname]
