- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Debug inventory role
      debug:
        msg: "test var: {{role}}"
    - name: Loop All Hosts
      debug:
        msg: "host is {{item}} {{ hostvars[item]['role'] }}"
      with_items: "{{ groups['all'] }}"
